# Generated by Django 6.0.3 on 2026-03-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='modelo_bike',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
